### ISSUE TITLE
Proposed unit tests

### ISSUE THREAD

**Issue by dbrunton** [LibraryOfCongress/bagit-java#45]
Run verifypayloadmanifests on a bag with valid / invalid / no payload manifests. Should return true / false / error or false.
    Create a zipped bag with an invalid bagit.txt file and run verifycomplete. Then try to delete the zip file. There should be no console output and no exception thrown. Repeat the same thing with a valid zipped bag.
    Create a folder with empty directories, some that are truly empty and some that contain .keep files. Run bag in place. The truly empty directories should be ignored (will not be present in the resulting bag) and the ones containing .keep files should be part of the bag. No exceptions should be thrown.

**Comment by johnscancella** [comment]
re-writing them:
given a valid bag
when verifypayloadmanifests is run on the bag
then true is returned

given a invalid bag because it has no payload manifests
when verifypayloadmanifests is run on the bag
then false is returned

given a zipped bag with an invalid bagit.txt file
when verifycomplete is run on the bag
then there is no exception thrown or console output

given a valid zipped bag 
when verifycomplete is run on the bag
then there is no exception thrown or console output

given an empty folder
when baginplace is run
then that folder should be ignored in the manifest and no exception thrown

given a folder that only contains a .keep file
when baginplace is run
then that folder should be included in the manifest and no exception thrown

**Comment by johnscancella** [comment]
I created a separate branch for adding these tests since the master branch is already past the 4.x series
