### ISSUE TITLE
always create tag manifest(s)

### ISSUE THREAD

**Issue by johnscancella** [LibraryOfCongress/bagit-java#76]
Even though the tag manifest(s) are optional they provide a lot of value. Therefore we should always be creating them when possible.

**Comment by smmorrissey** [comment]
What if there are no tag files? or do you consider manifest-<>.txt to be a tag file that should be in at least one tag manifest file?

**Comment by acdha** [comment]
@smmorrissey That's correct – the spec defines the payload manifest file as a tag file, so we should always have at least one. I was discussing that with @johnscancella because without a tag manifest it might not be possible to detect errors like a truncated manifest file (payload-oxum is also optional).

**Comment by johnscancella** [comment]
any file not in the `data` directory is a tag file. So at the very least there should be 2 files in a tag manifest, namely `bagit.txt` and `manifest-<ALGORITHM>.txt`
