### ISSUE TITLE
Question: Any one has any reference to any documentation on how I can use it?

### ISSUE THREAD

**Issue by siddikachowdhury** [LibraryOfCongress/bagit-java#9]
Looking for some example of how I can use this tool for bagit manifest parse or data extraction. I could not find any documentation anywhere, any help to guide me will greatly appreciated!

**Comment by johnscancella** [comment]
@siddikachowdhury sorry this is such a late response, but bagit-java is more about creating and validating a bag then parsing or exacting (meta)data. Not knowing what you are doing with the parsing, it is hard to give a suggestion as to where to go to find your answer. However, you might want to look into the java desktop app [bagger](https://github.com/LibraryOfCongress/bagger) which handles displaying already created bags and modifying them.

@mjordan I updated the README to include where to look for the built bagger application now that we are using gradle instead of maven.
